version: '3.9'
services:

  ### Mongos Servers
  mongos1:
    image: mongo:${MONGE_TAG}
    container_name: mongos1
    hostname: mongos1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    command: mongos --configdb configReplica/config1:27017,config2:27017,config3:27017 --bind_ip 0.0.0.0 --port 27017
    depends_on:
      - config1
      - config2
      - config3
    ports:
      - 27017:27017

  mongos2:
    image: mongo:${MONGE_TAG}
    container_name: mongos2
    hostname: mongos2
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    command: mongos --configdb configReplica/config1:27017,config2:27017,config3:27017 --bind_ip 0.0.0.0 --port 27017
    depends_on:
      - config1
      - config2
      - config3
    ports:
      - 27018:27017

  mongos3:
    image: mongo:${MONGE_TAG}
    container_name: mongos3
    hostname: mongos3
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    command: mongos --configdb configReplica/config1:27017,config2:27017,config3:27017 --bind_ip 0.0.0.0 --port 27017
    depends_on:
      - config1
      - config2
      - config3
    ports:
      - 27019:27017


######################################################################################################################
######################################################################################################################
######################################################################################################################
  ### Mongodb Config Servers
  config1:
    image: mongo:${MONGE_TAG}
    container_name: config1
    hostname: config1
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    command: mongod --configsvr --replSet configReplica --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/config1:/data/db
    ports:
      - 10011:27017

  config2:
    image: mongo:${MONGE_TAG}
    container_name: config2
    hostname: config2
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    command: mongod --configsvr --replSet configReplica --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/config2:/data/db
    ports:
      - 10012:27017

  config3:
    image: mongo:${MONGE_TAG}
    container_name: config3
    hostname: config3
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    command: mongod --configsvr --replSet configReplica --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/config3:/data/db
    ports:
      - 10013:27017

######################################################################################################################
######################################################################################################################
######################################################################################################################
  ### Mongodb Shard Servers
  shard11:
    image: mongo:${MONGE_TAG}
    container_name: shard11
    hostname: shard11
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    command: mongod --shardsvr --replSet rs1 --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/data-shard11:/data/db
    ports:
      - 20011:27017

  shard12:
    image: mongo:${MONGE_TAG}
    container_name: shard12
    hostname: shard12
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    command: mongod --shardsvr --replSet rs1 --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/data-shard12:/data/db
    ports:
      - 20012:27017

  shard13:
    image: mongo:${MONGE_TAG}
    container_name: shard13
    hostname: shard13
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    command: mongod --shardsvr --replSet rs1 --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/data-shard13:/data/db
    ports:
      - 20013:27017


  shard21:
    image: mongo:${MONGE_TAG}
    container_name: shard21
    hostname: shard21
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    command: mongod --shardsvr --replSet rs2 --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/data-shard21:/data/db
    ports:
      - 20021:27017

  shard22:
    image: mongo:${MONGE_TAG}
    container_name: shard22
    hostname: shard22
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    command: mongod --shardsvr --replSet rs2 --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/data-shard22:/data/db
    ports:
      - 20022:27017

  shard23:
    image: mongo:${MONGE_TAG}
    container_name: shard23
    hostname: shard23
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    command: mongod --shardsvr --replSet rs2 --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/data-shard23:/data/db
    ports:
      - 20023:27017


  ### mongo-express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    environment:
#      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongos1:27017/
      ME_CONFIG_MONGODB_URL: mongodb://mongos1:27017
    depends_on:
      - mongos1
    ports:
      - 8081:8081
