version: '3.9'
services:

  # Mongos Servers
  mongos1:
    image: mongo:${MONGE_TAG}
    container_name: mongos1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    command: mongos --configdb configReplica/config1:10011,config2:10012,config3:10013 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 27017:27017


  mongos2:
    image: mongo:${MONGE_TAG}
    container_name: mongos2
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    command: mongos --configdb configReplica/config1:10011,config2:10012,config3:10013 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 27018:27017


  mongos3:
    image: mongo:${MONGE_TAG}
    container_name: mongos3
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    command: mongos --configdb configReplica/config1:10011,config2:10012,config3:10013 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 27019:27017


  ### Mongodb Config Servers
  config1:
    image: mongo:${MONGE_TAG}
    container_name: config1
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    command: mongod --configsvr --replSet configReplica --port 27017 --dbpath /data/db
    volumes:
      - ./mongodb/config1:/data/db
    ports:
      - 10011:27017


  config2:
    image: mongo:${MONGE_TAG}
    container_name: config2
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    command: mongod --configsvr --replSet configReplica --port 27017 --dbpath /data/db
    volumes:
      - ./mongodb/config2:/data/db
    ports:
      - 10012:27017


  config3:
    image: mongo:${MONGE_TAG}
    container_name: config3
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    command: mongod --configsvr --replSet configReplica --port 27017 --dbpath /data/db
    volumes:
      - ./mongodb/config3:/data/db
    ports:
      - 10013:27017


  ### Mongodb Shard Servers
  shard1primary:
    image: mongo:${MONGE_TAG}
    container_name: shard1primary
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    command: mongod --shardsvr --replSet rs1 --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/data-mongo11:/data/db
    ports:
      - 20011:27017


  shard1secondary:
    image: mongo:${MONGE_TAG}
    container_name: shard1secondary
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    command: mongod --shardsvr --replSet rs1 --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/data-mongo12:/data/db
    ports:
      - 20012:27017


  shard1arbiter:
    image: mongo:${MONGE_TAG}
    container_name: shard1arbiter
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    command: mongod --shardsvr --replSet rs1 --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/data-mongo13:/data/db
    ports:
      - 20013:27017


  shard2primary:
    image: mongo:${MONGE_TAG}
    container_name: shard2primary
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    command: mongod --shardsvr --replSet rs2 --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/data-mongo21:/data/db
    ports:
      - 20021:27017


  shard2secondary:
    image: mongo:${MONGE_TAG}
    container_name: shard2secondary
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    command: mongod --shardsvr --replSet rs2 --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/data-mongo22:/data/db
    ports:
      - 20022:27017


  shard2arbiter:
    image: mongo:${MONGE_TAG}
    container_name: shard2arbiter
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    command: mongod --shardsvr --replSet rs2 --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - ./mongodb/data-mongo23:/data/db
    ports:
      - 20023:27017


#  ### mongo-express
#  mongo-express:
#    image: mongo-express:latest
#    container_name: mongo-express
#    restart: always
#    environment:
#      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo1:27017/
#    depends_on:
#      - mongo1
#    ports:
#      - 8080:8081
#    expose:
#      - 8081
#    networks:
#      - mongo-net


### docker network create mongo-net
networks:
  mongo-net: